"""
Cryptographic constants and parameters for SplitSmart application.
"""

# Key sizes (in bits)
RSA_KEY_SIZE = 2048
AES_KEY_SIZE = 256  # bits
DH_KEY_SIZE = 2048

# Hash algorithm
HASH_ALGORITHM = "SHA256"

# Signature padding
SIGNATURE_ALGORITHM = "RSA-PSS"  # or "Ed25519"

# AES-GCM parameters
GCM_NONCE_SIZE = 12  # bytes (96 bits recommended for GCM)
GCM_TAG_SIZE = 16    # bytes (128 bits)

# Key derivation
KDF_ALGORITHM = "HKDF"
KDF_HASH = "SHA256"
KDF_INFO = b"SplitSmart-v1"

# Session parameters
SESSION_TIMEOUT = 3600  # seconds (1 hour)

# Replay protection
COUNTER_INITIAL_VALUE = 0
TIMESTAMP_TOLERANCE = 300  # seconds (5 minutes)

# Hash chain
GENESIS_HASH = "SplitSmart Genesis Block"

# File paths
KEYS_DIR = "keys"
DATA_DIR = "data"
DB_FILE = "data/splitsmart.db"

# Protocol message types
MSG_TYPE_CLIENT_HELLO = "CLIENT_HELLO"
MSG_TYPE_SERVER_HELLO = "SERVER_HELLO"
MSG_TYPE_EXPENSE_SUBMIT = "EXPENSE_SUBMIT"
MSG_TYPE_EXPENSE_RESPONSE = "EXPENSE_RESPONSE"
MSG_TYPE_LEDGER_REQUEST = "LEDGER_REQUEST"
MSG_TYPE_LEDGER_RESPONSE = "LEDGER_RESPONSE"
MSG_TYPE_BALANCE_REQUEST = "BALANCE_REQUEST"
MSG_TYPE_BALANCE_RESPONSE = "BALANCE_RESPONSE"
MSG_TYPE_ERROR = "ERROR"

# Error codes
ERROR_INVALID_SIGNATURE = "INVALID_SIGNATURE"
ERROR_REPLAY_DETECTED = "REPLAY_DETECTED"
ERROR_INVALID_COUNTER = "INVALID_COUNTER"
ERROR_DECRYPTION_FAILED = "DECRYPTION_FAILED"
ERROR_HASH_CHAIN_BROKEN = "HASH_CHAIN_BROKEN"
ERROR_USER_NOT_FOUND = "USER_NOT_FOUND"
ERROR_INVALID_MESSAGE = "INVALID_MESSAGE"
